#
#                                     d8888b. d8888b. d88888b .d8888.         .88b  d88.  .d8b.   d888b  d8b   db d88888b d888888b
#                                     88  `8D 88  `8D 88'     88'  YP         88'YbdP`88 d8' `8b 88' Y8b 888o  88 88'     `~~88~~'
#                                     88oodD' 88oodD' 88ooo   `8bo.           88  88  88 88ooo88 88      88V8o 88 88ooooo    88
#                                     88~~~   88~~~   88~~~     `Y8b.         88  88  88 88~~~88 88  ooo 88 V8o88 88~~~~~    88
#                                     88      88      88      db   8D         88  88  88 88   88 88. ~8~ 88  V888 88.        88
#                                     88      88      YP      `8888Y' C88888D YP  YP  YP YP   YP  Y888P  VP   V8P Y88888P    YP
#

#####
##   ##     ##                                     ##
##   ##  ####   ##   ## ##   ## ##   ## ##   ## ##   ##   ##   ##  ####    #####  ##   ## ##   ## ######
##   ## ##      ##   ## ##   ## ##   ## ##   ## ##  ###   ### ###     ##       ## ##   ## ##  ###   ##
##   ## ######  ####  #  ###### ####### ####  # ## # ##   ## # ##  #####   #####  ####### ## # ##   ##
##   ## ##   ## ##  # #      ## ##   ## ##  # # ###  ##   ##   ## ##  ##  ##      ##   ## ###  ##   ##
 #####   #####  ####  #      ## ##   ## ####  # ##   ##   ##   ##  ######  ###### ##   ## ##   ##   ##
magnet:
  material: player_head
  head_value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWJhOGViYzRjNmE4MTczMDk0NzQ5OWJmN2UxZDVlNzNmZWQ2YzFiYjJjMDUxZTk2ZDM1ZWIxNmQyNDYxMGU3In19fQ=="
  lore:
    - "<yellow>Притягивает предметы лежащие предметы"
    - "<yellow>Радиус: <radius> блоков"
  name: "<blue>Маг<red>нит"

######
##   ##           ####
##   ##  ####        ## ##   ## ##   ##  #####
######      ##    ##### ##  ### ##   ## ##
##       #####   ##  ## ## # ## ##   ## ##
##      ##  ##  ##   ## ###  ##  ###### ##
##       ######  #####  ##   ##      ##  #####
                                #####
radius: 3

 #####
##   ##
##      ##   ##  #####  ######   #####   #####  ######  ##        ######  ######  ##   ## ######    ##### ## # ##  #####  ##   ## ##   ##   #####
##      ##  ##  ##   ## ##   ## ##   ## ##        ##    ##        ##   ## ##   ## ##  ###   ##     ##  ##  # # #  ##   ## ##   ## ##  ###  ##  ##
##      #####   ##   ## ######  ##   ## ##        ##    ######    ##   ## ######  ## # ##   ##      #####   ###   ######  ####### ## # ##   #####
##   ## ##  ##  ##   ## ##      ##   ## ##        ##    ##   ##   ##   ## ##      ###  ##   ##     ##  ##  # # #  ##      ##   ## ###  ##  ##  ##
 #####  ##   ##  #####  ##       #####   #####    ##    ######    ##   ## ##      ##   ##   ##    ##   ## ## # ##  #####  ##   ## ##   ## ##   ##
speed: 0.3